### PR TITLE
feat: implement escaping/quoting rules for shell (#81)

### LINKED ISSUE #81: [Bounty] Support shell value quoting
Our [starbase_shell](https://github.com/moonrepo/starbase/tree/master/crates/shell) crate supports many CLI shells for formatting environment variables and appending `PATH` using shell specific syntax. The current implementation "works" but it assumes the formatted values are trivial, and do not include non-trivial values (spaces, required escaping, etc).

We should add a `Shell.quote` method to each shell, that follows the escaping/quoting rules of that shell, since all shells have their own custom syntax and rules.

```rust
pub trait Shell {
    // ...
    fn quote(&self, value: &str) -> String;
}
```

Furthermore, existing methods should be updated to use the quoting. For example:

```rust
// Before
fn format_env_set(&self, key: &str, value: &str) -> String {
    format!(r#"export {key}="{value}";"#)
}

// After
fn format_env_set(&self, key: &str, value: &str) -> String {
    format!("export {}={};", self.quote(key), self.quote(value))
}
```

## Requirements

- Ideally the quoting is incremental. For example, in Bash, if passed a simple value, it's not quoted.

```
export KEY=value
```

But if it contains values that need quoting, then wrap with quotes.

```
export KEY="value with spaces"
```

And if it really needs special quoting syntax for complex values, then finally use that.

```
export KEY=$'value with spaces and escapes, etc'
```

- Try to avoid pulling in additional dependencies. At maximum, only 1 dependency is allowed.

### PR DESCRIPTION
**Pull request by abhishek818**
changes done for bash based shells first
several todos left

fixes #81 
/claim #81

### CODE REVIEW

**Comment by abhishek818** [comment]
@milesj  tagging you just for a heads up. 
If you like this current work, perhaps assign me since this is a good enough big feature (not that much , but still), 
Anyways will continue my work on this..

**Comment by varshith257** [comment]
@abhishek818 I wanted to touch base regarding the work we're both tackling. I've been heavily invested in resolving the issues and making progress.  I'm currently actively engaged in resolving the issues and making progress. I kindly request that you hold off on proceeding with this particular task until I've had a chance to complete my attempt. If for any reason I decide not to continue, I'll let you know, and you're welcome to take it forward.

Hope you consider it @abhishek818

**Comment by abhishek818** [comment]
@varshith257 bro but mine is totally a different implementation here. And I believe there are always two types of repos : 1. Where a person is assigned a issue first to let only that person complete or abondon it.
2. Where anyone interested can take a chance and first complete working PR makes it.

I was also working on this issue since first day but never commented 'attempt' as I wanted to have a working implementation first.

Would have really abondoned this but I see my current work done till now as more better approach for this..

CC: @milesj ..

**Comment by varshith257** [comment]
@abhishek818 I know it but I already have done some progress and let me have a chance to complete this attempt. If will give up on this and let you know this and I am ensuring of no duplicate efforts of us towards it :)

**Comment by milesj** [comment]
Will be going with the other PR: https://github.com/moonrepo/starbase/pull/84

Nothing wrong with this PR at all, I just had to pick one :P 

Here's a tip for the work so far.

**Comment by abhishek818** [comment]
Thanks @milesj for the tip.
@varshith257 best of luck to you but also have a look at this pr changes to pick anything you find better.

**Pull request closed without merging**
